/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 헬스체크
         * @description 프로세스 생존 확인. 인증 없음.
         */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 링크 목록 조회
         * @description keyset 커서 페이지네이션 (OFFSET 금지). `(created_at, id)` 인덱스를 타므로 링크 10만 건에서도 p99 < 50ms.
         */
        get: operations["listLinks"];
        put?: never;
        /**
         * 링크 저장
         * @description `INSERT INTO links` + `INSERT INTO jobs(kind='scrape')`를 한 트랜잭션으로 커밋하고 즉시 응답한다 (p99 < 50ms). 스크랩·태깅·썸네일은 백그라운드 잡으로 처리된다. `url_hash`(SHA-256(url)) 기반으로 멱등하다 — 클라이언트가 같은 요청을 재시도해도 중복 생성이 없다 (중복 시 200 `duplicate:true`). 소프트 삭제된 링크의 URL을 다시 저장하면 같은 행을 복원(pending 복귀, note 교체, scrape 재-enqueue)하고 신규 저장처럼 201로 응답한다.
         */
        post: operations["createLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/links/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 링크 id */
                id: components["parameters"]["LinkId"];
            };
            cookie?: never;
        };
        /**
         * 링크 상세 조회
         * @description 목록 항목 전체 필드 + author, published_at, duration_sec, word_count, lang, error, jobs 요약.
         */
        get: operations["getLink"];
        put?: never;
        post?: never;
        /**
         * 링크 삭제 (소프트)
         * @description 소프트 삭제 — `deleted_at`만 기록하며 행은 남는다. 이후 목록/검색/상세에서 제외된다.
         */
        delete: operations["deleteLink"];
        options?: never;
        head?: never;
        /**
         * 링크 수정 (메모/태그)
         * @description `note` 전달 시 메모 교체. `tags`(태그 이름 배열) 전달 시 이 링크의 태그를 전체 교체한다 — 추가분은 `link_tags(source='manual', confidence=NULL)` + `tag_feedback(added)`, 제거분은 `tag_feedback(removed)` 기록. tag_feedback은 M5 재랭킹 학습 데이터다. `tags`가 `null`이거나 생략되면 태그를 유지하고, 빈 배열 `[]`이면 전체 제거로 처리한다.
         */
        patch: operations["updateLink"];
        trace?: never;
    };
    "/api/v1/links/{id}/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 열람 기록
         * @description 이 링크를 열었다는 사실만 기록한다(`opened_at`). 클라이언트는 fire-and-forget으로 부르고 실패해도 재시도하지 않는다 — 저장 경로 밖이라 p99 게이트와 무관하고, 한 번 놓친 열람 기록이 아카이브를 손상시키지 않는다.
         *     **횟수는 세지 않는다.** 이 신호는 푸시포인트를 통과한 열람만 잡으므로(브라우저 히스토리·원본 앱 직접 열기는 잡히지 않는다) 구조적으로 과소집계이고, 비율이나 지표로 쓰면 틀린 결론을 만든다. 링크별 사실로만 쓴다.
         */
        post: operations["markOpened"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/links/{id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 실패 링크 재시도
         * @description `status='failed'`인 링크의 잡을 다시 enqueue한다. 링크는 `pending`으로 되돌아가고 워커가 처음부터 다시 처리한다. `failed` 상태가 아닌 링크는 400.
         */
        post: operations["retryLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 태그 사전 조회
         * @description 통제된 태그 사전 전체 + 사용 수(`link_count`, 삭제되지 않은 링크 기준). `facet`은 여기에만 실린다 — `LinkTag`에는 없으므로 클라이언트가 이 응답을 `Map<tagId, facet>`으로 캐시해 목록 행의 칩 색을 해석한다 (링크당 태그 수만큼 페이로드가 늘어나는 것을 피한다).
         */
        get: operations["listTags"];
        put?: never;
        /**
         * 태그 생성
         * @description `name`은 대소문자 무시 UNIQUE — 중복이면 400. `facet`은 optional이며 생략하면 `neutral`이다 (클라이언트가 칩 색을 고르는 유일한 입력).
         */
        post: operations["createTag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tags/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 태그 id */
                id: components["parameters"]["TagId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 태그 삭제
         * @description 사전에서 제거한다. `link_tags` 연결은 FK CASCADE로 함께 삭제된다.
         */
        delete: operations["deleteTag"];
        options?: never;
        head?: never;
        /**
         * 태그 수정
         * @description `name`, `aliases`, `facet` 모두 optional (전달한 필드만 교체). `aliases`는 규칙 기반 태거의 매칭 대상 — alias를 잘 채우는 것이 태깅 정확도를 올리는 가장 싼 방법이다. `facet`은 태그 분류 축이며, 이 값을 바꾸면 모든 클라이언트에서 그 태그의 칩 색이 바뀐다.
         */
        patch: operations["updateTag"];
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 검색
         * @description `q`가 3자 이상이면 FTS5 trigram MATCH + bm25 랭킹 (응답 `mode: "fts"`). 3자 미만은 에러(400)가 아니라 LIKE 폴백이다 — links 테이블의 title/note/description을 LIKE 스캔(`%`·`_` ESCAPE 처리)하고 `created_at DESC` 정렬, 응답 `mode: "like"`에 모든 항목의 `rank`는 null (실측 10만 행 풀스캔 37ms로 예산 내).
         */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sheets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 스프레드시트 연결 상태
         * @description Google 스프레드시트 연결 여부와 마지막 동기화 결과. 연결은 CLI(`pushpoint sheets-setup`)에서 하고 이 API는 **상태 조회와 실행만** 한다 — 연결에는 브라우저에서 구글 승인을 밟는 단계가 있어 서버가 대신할 수 없다.
         */
        get: operations["getSheetsStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sheets/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 지금 동기화
         * @description 아카이브 전량을 시트에 다시 쓴다(교체). 동기 호출이며 링크 수에 비례해 몇 초 걸릴 수 있다 — 저장 API가 아니므로 p99 게이트 대상이 아니다. 연결돼 있지 않으면 409.
         */
        post: operations["syncSheets"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 통계 조회
         * @description iOS 위젯용 데이터를 한 번의 호출로 제공한다 (구현 완료 — 위젯 활용은 M6).
         */
        get: operations["getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/thumbs/{dir}/{file}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 썸네일 정적 서빙
         * @description `data/thumbs/` 아래의 썸네일 JPEG(단일 사이즈, 최대 폭 640px, q80)를 그대로 서빙한다. 경로 형식은 `{url_hash 앞 2자리}/{url_hash}.jpg` — 목록/상세 응답의 `thumb_url`이 정확히 이 경로를 가리킨다. 인증 면제 — Tailscale이 네트워크 경계를 이루고, iOS AsyncImage가 커스텀 헤더를 지원하지 않기 때문이다.
         */
        get: operations["getThumb"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description unix epoch seconds */
        EpochSeconds: number;
        /** @description unix epoch seconds */
        EpochSecondsNullable: number | null;
        /**
         * @description 링크 처리 파이프라인 상태
         * @enum {string}
         */
        LinkStatus: "pending" | "scraping" | "tagging" | "done" | "failed";
        /**
         * @description 도메인·URL 패턴 휴리스틱으로 판정한 콘텐츠 종류
         * @enum {string}
         */
        ContentType: "video" | "article" | "post" | "other";
        /**
         * @description 잡 상태
         * @enum {string}
         */
        JobStatus: "pending" | "running" | "done" | "failed";
        /**
         * @description 태그 분류 축. 클라이언트는 이 값만으로 칩 색 토큰을 고른다 (색 값 자체는 계약에 없다 — 라이트/다크 2벌이라 표현은 각 클라이언트가 소유한다). 사전에 없는 새 태그는 neutral로 태어난다. 생략 시 동작은 오퍼레이션마다 다르다 — `createTag`는 `neutral`로 생성하고, `updateTag`는 기존 값을 유지한다. (그래서 이 스키마에는 `default`를 두지 않는다. 두면 PATCH에서 "생략 = neutral"로 잘못 읽힌다.)
         * @enum {string}
         */
        TagFacet: "craft" | "media" | "life" | "neutral";
        /** @description 링크에 부착된 태그 (부착 출처·신뢰도 포함) */
        LinkTag: {
            id: number;
            name: string;
            /**
             * @description 부착 출처 — rules(Phase A) / embed(Phase B) / manual(사용자)
             * @enum {string}
             */
            source: "rules" | "embed" | "manual";
            /** @description 태거의 신뢰 점수. manual이면 null */
            confidence: number | null;
        };
        /** @description 링크 목록 항목 */
        Link: {
            id: number;
            url: string;
            domain: string;
            title: string;
            /** @description 목록에서는 200자로 절단 (전체는 상세 조회) */
            description: string;
            content_type: components["schemas"]["ContentType"];
            /** @description `/thumbs/{dir}/{file}` 형태의 서버 상대 경로. 썸네일 없으면 null */
            thumb_url: string | null;
            status: components["schemas"]["LinkStatus"];
            tags: components["schemas"]["LinkTag"][];
            /** @description 개인 메모 */
            note: string;
            created_at: components["schemas"]["EpochSeconds"];
        };
        /** @description 링크 상세 — 목록 항목 전체 필드 + 메타·에러·잡 요약 */
        LinkDetail: components["schemas"]["Link"] & {
            author: string;
            /** @description 본문에서 고른 핵심 문장 2~3개를 개행으로 이은 추출식 요약 (LLM 없이 원문 문장을 그대로 선택하므로 환각 0). 본문이 얇거나 산문이 부족하거나 description과 사실상 같으면 빈 문자열이며, 그때 클라이언트는 요약 영역을 그리지 않는다. 목록(Link)·검색(SearchResult)에는 싣지 않는다 — 요약은 원문 대체재가 아니라 "열까 말까"의 판단 보조다 */
            summary: string;
            published_at: components["schemas"]["EpochSecondsNullable"];
            duration_sec: number | null;
            word_count: number | null;
            lang: string;
            /** @description 마지막으로 이 링크를 연 시각. 한 번도 안 열었으면 null. **목록 항목(`Link`)에는 넣지 않는다** — 카드에 표시할 자리가 없으므로(상태는 2px 레일뿐) 목록 페이로드를 키울 이유가 없다. */
            opened_at: components["schemas"]["EpochSeconds"] | null;
            /** @description 최종 실패 사유. 실패 없으면 빈 문자열 */
            error: string;
            /** @description 이 링크에 연결된 잡 상태 요약. 해당 kind의 잡이 아직 없으면 필드 생략 (scrape 잡은 저장 트랜잭션에서 항상 생성되므로 필수). thumb은 best-effort — failed여도 링크 status에 영향 없음 */
            jobs: {
                scrape: components["schemas"]["JobStatus"];
                tag?: components["schemas"]["JobStatus"];
                thumb?: components["schemas"]["JobStatus"];
            };
        };
        /** @description 링크 저장 요청. title·description·body_text는 **클라이언트 캡처**용 optional 필드다 — 서버가 fetch할 수 없는 페이지(SPA·봇 차단·로그인 벽)에서 이미 렌더된 콘텐츠를 가진 클라이언트(브라우저 확장·iOS Share Extension)가 함께 보낸다. 서버는 길이를 **절단**할 뿐 초과를 400으로 거부하지 않는다(클라이언트가 룬/바이트 경계를 서버와 맞출 방법이 없다). */
        LinkInput: {
            url: string;
            /** @description 개인 메모 (optional) */
            note?: string;
            /** @description 클라이언트가 캡처한 제목 (optional, 512바이트로 절단) */
            title?: string;
            /** @description 클라이언트가 캡처한 설명 (optional, 2048바이트로 절단) */
            description?: string;
            /** @description 클라이언트가 추출한 본문 평문 (optional, 32KB로 절단). 값이 있으면 서버는 이 링크의 본문 출처를 'client'로 표시하고, 이후 스크랩이 제목·설명·본문을 덮어쓰지 않는다. 태깅·요약이 이 본문을 입력으로 쓴다 — 그래서 스크랩이 실패해도 태그·요약이 나온다. */
            body_text?: string;
            /** @description 발행자가 스스로 붙인 분류 (optional, 512바이트로 절단). `meta[name=keywords]`, `news_keywords`, `article:section`, `article:tag`, JSON-LD `articleSection`을 모아 콤마로 이어 붙인 값이다. **도메인 맵과 달리 사이트별 등록이 필요 없다** — 발행자가 알려주는 값이라 등록되지 않은 사이트에서도 동작한다. 태거가 제목과 같은 가중치를 준다. 서버도 스크랩할 때 같은 값을 뽑으므로, 이 필드는 서버가 fetch할 수 없는 페이지를 위한 것이다 (title·description·body_text와 같은 이유). */
            keywords?: string;
        };
        /** @description 링크 수정 요청 — note는 교체, tags는 전체 교체 (부분 추가/삭제 API 없음) */
        LinkUpdateInput: {
            note?: string;
            /** @description 태그 이름 배열. 존재하지 않는 태그 이름이면 400 */
            tags?: string[];
        };
        /** @description 스프레드시트 연결 상태와 마지막 동기화 결과 */
        SheetsStatus: {
            /** @description 연결됐는지. false면 나머지 필드는 비어 있다 */
            connected: boolean;
            /** @description 시트 주소. 없으면 빈 문자열 */
            sheet_url?: string;
            /** @description 마지막 동기화 시각(unix epoch 초). 한 번도 안 했으면 null */
            last_sync_at?: number | null;
            /** @description 마지막에 쓴 링크 수 */
            last_rows?: number;
            /** @description 마지막 동기화가 실패했다면 그 이유. 성공했으면 빈 문자열 */
            last_error?: string;
        };
        /** @description 커서 페이지네이션 응답 래퍼 */
        LinkPage: {
            links: components["schemas"]["Link"][];
            /** @description 다음 페이지 커서. null이면 마지막 페이지 */
            next_cursor: string | null;
        };
        /** @description 검색 결과 항목 — 목록 항목 + bm25 rank */
        SearchResult: components["schemas"]["Link"] & {
            /** @description bm25 점수 (낮을수록 관련도 높음). mode가 like면 null */
            rank: number | null;
        };
        /** @description 검색 응답 래퍼 — 커서 페이지네이션 + 검색 경로(mode) */
        SearchPage: {
            /**
             * @description 검색 경로: q 3자 이상 = fts (FTS5 MATCH + bm25), 3자 미만 = like (LIKE 폴백, created_at DESC)
             * @enum {string}
             */
            mode: "fts" | "like";
            links: components["schemas"]["SearchResult"][];
            /** @description 다음 페이지 커서. null이면 마지막 페이지 */
            next_cursor: string | null;
        };
        /** @description 태그 사전 항목 + 사용 수 */
        Tag: {
            id: number;
            /** @description 태그 이름 (대소문자 무시 UNIQUE) */
            name: string;
            /** @description 동의어·영문/한글 표기 — Phase A 문자열 매칭의 재료 */
            aliases: string[];
            /** @description 이 태그가 붙은 (삭제되지 않은) 링크 수 */
            link_count: number;
            facet: components["schemas"]["TagFacet"];
        };
        /** @description 태그 생성/수정 요청 (생성 시 name 필수) */
        TagInput: {
            name?: string;
            aliases?: string[];
            facet?: components["schemas"]["TagFacet"];
        };
        /** @description 통계 응답 (iOS 위젯용 — 위젯 활용은 M6) */
        Stats: {
            total_links: number;
            links_this_week: number;
            by_tag: {
                name: string;
                count: number;
            }[];
            /** @description 최근 30일 일별 저장 수 */
            by_day: {
                /** @description YYYY-MM-DD (localtime) */
                date: string;
                count: number;
            }[];
        };
        /** @description 공통 에러 형식 — 코드는 4개가 전부 (단일 사용자라 forbidden/rate_limit 없음) */
        Error: {
            error: {
                /** @enum {string} */
                code: "unauthorized" | "not_found" | "invalid_input" | "internal";
                message: string;
            };
        };
    };
    responses: {
        /** @description 잘못된 요청 (`invalid_input`) */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "invalid_input",
                 *         "message": "url is required"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description API 키 누락 또는 불일치 (`unauthorized`) */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "unauthorized",
                 *         "message": "invalid api key"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 리소스 없음 — 소프트 삭제된 링크 포함 (`not_found`) */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "not_found",
                 *         "message": "link not found"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 서버 내부 오류 (`internal`) — 핸들러가 처리하지 못한 에러의 공통 종착점이다. `GET /healthz`만 이 응답이 없다 (조건 없는 단일 반환이라 실패 경로가 없다). `GET /thumbs/{dir}/{file}`은 인증만 면제일 뿐 500 면제는 아니다 — 파일 열기·stat 실패 시 500을 낸다. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "internal",
                 *         "message": "internal server error"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description 링크 id */
        LinkId: number;
        /** @description 태그 id */
        TagId: number;
        /** @description 이전 응답의 `next_cursor` 값. 첫 페이지는 생략. 불투명(opaque) 토큰. */
        Cursor: string;
        /** @description 페이지 크기 */
        Limit: number;
        /** @description 태그 이름 필터 */
        TagFilter: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 프로세스 정상 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok"
                     *     }
                     */
                    "application/json": {
                        /** @constant */
                        status: "ok";
                    };
                };
            };
        };
    };
    listLinks: {
        parameters: {
            query?: {
                /** @description 이전 응답의 `next_cursor` 값. 첫 페이지는 생략. 불투명(opaque) 토큰. */
                cursor?: components["parameters"]["Cursor"];
                /** @description 페이지 크기 */
                limit?: components["parameters"]["Limit"];
                /** @description 태그 이름 필터 */
                tag?: components["parameters"]["TagFilter"];
                /** @description 링크 상태 필터 */
                status?: components["schemas"]["LinkStatus"];
                /** @description `true`면 아직 열지 않은 링크만. 양방향 불리언이 아니다 — "다시 읽은 것" 필터는 쓰이지 않는다. 부분 인덱스가 있어 keyset 커서가 그대로 탄다. */
                unopened?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 링크 목록 페이지 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    createLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkInput"];
            };
        };
        responses: {
            /** @description 동일 `url_hash`가 이미 존재 — 새로 만들지 않고 기존 id를 반환한다. 저장된 본문이 서버 출처인데 요청이 클라이언트 본문(body_text)을 실어 오면 제목·설명·본문을 **1회 보충**하고 태깅을 다시 돌린다(이미 클라이언트 본문이면 아무것도 하지 않는다). 반복 호출은 같은 상태로 수렴하므로 재시도는 여전히 안전하다. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": 987,
                     *       "duplicate": true
                     *     }
                     */
                    "application/json": {
                        id: number;
                        /** @constant */
                        duplicate: true;
                    };
                };
            };
            /** @description 신규 저장 완료 (scrape 잡 enqueue됨) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": 1234,
                     *       "status": "pending",
                     *       "created_at": 1752980000
                     *     }
                     */
                    "application/json": {
                        id: number;
                        status: components["schemas"]["LinkStatus"];
                        created_at: components["schemas"]["EpochSeconds"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 링크 id */
                id: components["parameters"]["LinkId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 링크 상세 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 링크 id */
                id: components["parameters"]["LinkId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 삭제 완료 (본문 없음) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    updateLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 링크 id */
                id: components["parameters"]["LinkId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkUpdateInput"];
            };
        };
        responses: {
            /** @description 수정 반영된 링크 상세 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    markOpened: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 링크 id */
                id: components["parameters"]["LinkId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 기록 완료 (본문 없음) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    retryLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 링크 id */
                id: components["parameters"]["LinkId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 재-enqueue 수락 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": 1234,
                     *       "status": "pending"
                     *     }
                     */
                    "application/json": {
                        id: number;
                        status: components["schemas"]["LinkStatus"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listTags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 태그 사전 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    createTag: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagInput"] & unknown;
            };
        };
        responses: {
            /** @description 생성된 태그 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 태그 id */
                id: components["parameters"]["TagId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 삭제 완료 (본문 없음) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    updateTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 태그 id */
                id: components["parameters"]["TagId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagInput"];
            };
        };
        responses: {
            /** @description 수정된 태그 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    search: {
        parameters: {
            query: {
                /** @description 검색어. 3자 이상 = FTS5, 3자 미만 = LIKE 폴백 (400 아님). */
                q: string;
                /** @description 태그 이름 필터 */
                tag?: components["parameters"]["TagFilter"];
                /** @description created_at 범위 시작 (unix epoch 초) */
                from?: number;
                /** @description created_at 범위 끝 (unix epoch 초) */
                to?: number;
                /** @description 이전 응답의 `next_cursor` 값. 첫 페이지는 생략. 불투명(opaque) 토큰 — 목록 커서와 검색 커서는 형식이 달라 서로 호환되지 않는다 (형식 불일치는 400). FTS 모드 커서는 bm25 rank 기반이라 페이지 사이에 쓰기가 발생하면 FTS 페이지 경계가 이동할 수 있다 (단일 사용자 규모에서 허용). */
                cursor?: string;
                /** @description 페이지 크기 */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 검색 결과 페이지 (`mode`로 검색 경로 표시) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getSheetsStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 연결 상태 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SheetsStatus"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    syncSheets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 동기화 결과 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SheetsStatus"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description 아직 연결되지 않음 (`pushpoint sheets-setup` 필요) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 통계 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stats"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getThumb: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description url_hash 앞 2자리 (hex)
                 * @example a3
                 */
                dir: string;
                /**
                 * @description `{url_hash}.jpg` 파일명
                 * @example a3f1b2c4d5e6f7a8a3f1b2c4d5e6f7a8a3f1b2c4d5e6f7a8a3f1b2c4d5e6f7a8.jpg
                 */
                file: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 썸네일 이미지 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
}
