/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 헬스체크
         * @description 프로세스 생존 확인. 인증 없음.
         */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 링크 목록 조회
         * @description keyset 커서 페이지네이션 (OFFSET 금지). `(created_at, id)` 인덱스를 타므로 링크 10만 건에서도 p99 < 50ms.
         */
        get: operations["listLinks"];
        put?: never;
        /**
         * 링크 저장
         * @description `INSERT INTO links` + `INSERT INTO jobs(kind='scrape')`를 한 트랜잭션으로 커밋하고 즉시 응답한다 (p99 < 50ms). 스크랩·태깅·썸네일은 백그라운드 잡으로 처리된다. `url_hash`(SHA-256(url)) 기반으로 멱등하다 — 클라이언트(Share Extension의 App Group 로컬 큐)가 같은 요청을 재시도해도 중복 생성이 없다 (중복 시 200 `duplicate:true`). 소프트 삭제된 링크의 URL을 다시 저장하면 같은 행을 복원(pending 복귀, note 교체, scrape 재-enqueue)하고 신규 저장처럼 201로 응답한다.
         */
        post: operations["createLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/links/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 링크 id */
                id: components["parameters"]["LinkId"];
            };
            cookie?: never;
        };
        /**
         * 링크 상세 조회
         * @description 목록 항목 전체 필드 + author, published_at, duration_sec, word_count, lang, error, jobs 요약.
         */
        get: operations["getLink"];
        put?: never;
        post?: never;
        /**
         * 링크 삭제 (소프트)
         * @description 소프트 삭제 — `deleted_at`만 기록하며 행은 남는다. 이후 목록/검색/상세에서 제외된다.
         */
        delete: operations["deleteLink"];
        options?: never;
        head?: never;
        /**
         * 링크 수정 (메모/태그)
         * @description `note` 전달 시 메모 교체. `tags`(태그 이름 배열) 전달 시 이 링크의 태그를 전체 교체한다 — 추가분은 `link_tags(source='manual', confidence=NULL)` + `tag_feedback(added)`, 제거분은 `tag_feedback(removed)` 기록. tag_feedback은 M5 재랭킹 학습 데이터다. `tags`가 `null`이거나 생략되면 태그를 유지하고, 빈 배열 `[]`이면 전체 제거로 처리한다.
         */
        patch: operations["updateLink"];
        trace?: never;
    };
    "/api/v1/links/{id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 실패 링크 재시도
         * @description `status='failed'`인 링크의 잡을 다시 enqueue한다. 링크는 `pending`으로 되돌아가고 워커가 처음부터 다시 처리한다. `failed` 상태가 아닌 링크는 400.
         */
        post: operations["retryLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 태그 사전 조회
         * @description 통제된 태그 사전 전체 + 사용 수(`link_count`, 삭제되지 않은 링크 기준).
         */
        get: operations["listTags"];
        put?: never;
        /**
         * 태그 생성
         * @description `name`은 대소문자 무시 UNIQUE — 중복이면 400.
         */
        post: operations["createTag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tags/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 태그 id */
                id: components["parameters"]["TagId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 태그 삭제
         * @description 사전에서 제거한다. `link_tags` 연결은 FK CASCADE로 함께 삭제된다.
         */
        delete: operations["deleteTag"];
        options?: never;
        head?: never;
        /**
         * 태그 수정
         * @description `name`, `aliases` 모두 optional. `aliases`는 규칙 기반 태거의 매칭 대상 — alias를 잘 채우는 것이 태깅 정확도를 올리는 가장 싼 방법이다.
         */
        patch: operations["updateTag"];
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 검색
         * @description `q`가 3자 이상이면 FTS5 trigram MATCH + bm25 랭킹 (응답 `mode: "fts"`). 3자 미만은 에러(400)가 아니라 LIKE 폴백이다 — links 테이블의 title/note/description을 LIKE 스캔(`%`·`_` ESCAPE 처리)하고 `created_at DESC` 정렬, 응답 `mode: "like"`에 모든 항목의 `rank`는 null (실측 10만 행 풀스캔 37ms로 예산 내).
         */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 통계 조회
         * @description iOS 위젯용 데이터를 한 번의 호출로 제공한다 (구현 완료 — 위젯 활용은 M6).
         */
        get: operations["getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/thumbs/{dir}/{file}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 썸네일 정적 서빙
         * @description `data/thumbs/` 아래의 썸네일 JPEG(단일 사이즈, 최대 폭 640px, q80)를 그대로 서빙한다. 경로 형식은 `{url_hash 앞 2자리}/{url_hash}.jpg` — 목록/상세 응답의 `thumb_url`이 정확히 이 경로를 가리킨다. 인증 면제 — Tailscale이 네트워크 경계를 이루고, iOS AsyncImage가 커스텀 헤더를 지원하지 않기 때문이다.
         */
        get: operations["getThumb"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description unix epoch seconds */
        EpochSeconds: number;
        /** @description unix epoch seconds */
        EpochSecondsNullable: number | null;
        /**
         * @description 링크 처리 파이프라인 상태
         * @enum {string}
         */
        LinkStatus: "pending" | "scraping" | "tagging" | "done" | "failed";
        /**
         * @description 도메인·URL 패턴 휴리스틱으로 판정한 콘텐츠 종류
         * @enum {string}
         */
        ContentType: "video" | "article" | "post" | "other";
        /**
         * @description 잡 상태
         * @enum {string}
         */
        JobStatus: "pending" | "running" | "done" | "failed";
        /** @description 링크에 부착된 태그 (부착 출처·신뢰도 포함) */
        LinkTag: {
            id: number;
            name: string;
            /**
             * @description 부착 출처 — rules(Phase A) / embed(Phase B) / manual(사용자)
             * @enum {string}
             */
            source: "rules" | "embed" | "manual";
            /** @description 태거의 신뢰 점수. manual이면 null */
            confidence: number | null;
        };
        /** @description 링크 목록 항목 */
        Link: {
            id: number;
            url: string;
            domain: string;
            title: string;
            /** @description 목록에서는 200자로 절단 (전체는 상세 조회) */
            description: string;
            content_type: components["schemas"]["ContentType"];
            /** @description `/thumbs/{dir}/{file}` 형태의 서버 상대 경로. 썸네일 없으면 null */
            thumb_url: string | null;
            status: components["schemas"]["LinkStatus"];
            tags: components["schemas"]["LinkTag"][];
            /** @description 개인 메모 */
            note: string;
            created_at: components["schemas"]["EpochSeconds"];
        };
        /** @description 링크 상세 — 목록 항목 전체 필드 + 메타·에러·잡 요약 */
        LinkDetail: components["schemas"]["Link"] & {
            author: string;
            published_at: components["schemas"]["EpochSecondsNullable"];
            duration_sec: number | null;
            word_count: number | null;
            lang: string;
            /** @description 최종 실패 사유. 실패 없으면 빈 문자열 */
            error: string;
            /** @description 이 링크에 연결된 잡 상태 요약. 해당 kind의 잡이 아직 없으면 필드 생략 (scrape 잡은 저장 트랜잭션에서 항상 생성되므로 필수). thumb은 best-effort — failed여도 링크 status에 영향 없음 */
            jobs: {
                scrape: components["schemas"]["JobStatus"];
                tag?: components["schemas"]["JobStatus"];
                thumb?: components["schemas"]["JobStatus"];
            };
        };
        /** @description 링크 저장 요청 */
        LinkInput: {
            url: string;
            /** @description 개인 메모 (optional) */
            note?: string;
        };
        /** @description 링크 수정 요청 — note는 교체, tags는 전체 교체 (부분 추가/삭제 API 없음) */
        LinkUpdateInput: {
            note?: string;
            /** @description 태그 이름 배열. 존재하지 않는 태그 이름이면 400 */
            tags?: string[];
        };
        /** @description 커서 페이지네이션 응답 래퍼 */
        LinkPage: {
            links: components["schemas"]["Link"][];
            /** @description 다음 페이지 커서. null이면 마지막 페이지 */
            next_cursor: string | null;
        };
        /** @description 검색 결과 항목 — 목록 항목 + bm25 rank */
        SearchResult: components["schemas"]["Link"] & {
            /** @description bm25 점수 (낮을수록 관련도 높음). mode가 like면 null */
            rank: number | null;
        };
        /** @description 검색 응답 래퍼 — 커서 페이지네이션 + 검색 경로(mode) */
        SearchPage: {
            /**
             * @description 검색 경로: q 3자 이상 = fts (FTS5 MATCH + bm25), 3자 미만 = like (LIKE 폴백, created_at DESC)
             * @enum {string}
             */
            mode: "fts" | "like";
            links: components["schemas"]["SearchResult"][];
            /** @description 다음 페이지 커서. null이면 마지막 페이지 */
            next_cursor: string | null;
        };
        /** @description 태그 사전 항목 + 사용 수 */
        Tag: {
            id: number;
            /** @description 태그 이름 (대소문자 무시 UNIQUE) */
            name: string;
            /** @description 동의어·영문/한글 표기 — Phase A 문자열 매칭의 재료 */
            aliases: string[];
            /** @description 이 태그가 붙은 (삭제되지 않은) 링크 수 */
            link_count: number;
        };
        /** @description 태그 생성/수정 요청 (생성 시 name 필수) */
        TagInput: {
            name?: string;
            aliases?: string[];
        };
        /** @description 통계 응답 (iOS 위젯용 — 위젯 활용은 M6) */
        Stats: {
            total_links: number;
            links_this_week: number;
            by_tag: {
                name: string;
                count: number;
            }[];
            /** @description 최근 30일 일별 저장 수 */
            by_day: {
                /** @description YYYY-MM-DD (localtime) */
                date: string;
                count: number;
            }[];
        };
        /** @description 공통 에러 형식 — 코드는 4개가 전부 (단일 사용자라 forbidden/rate_limit 없음) */
        Error: {
            error: {
                /** @enum {string} */
                code: "unauthorized" | "not_found" | "invalid_input" | "internal";
                message: string;
            };
        };
    };
    responses: {
        /** @description 잘못된 요청 (`invalid_input`) */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "invalid_input",
                 *         "message": "url is required"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description API 키 누락 또는 불일치 (`unauthorized`) */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "unauthorized",
                 *         "message": "invalid api key"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 리소스 없음 — 소프트 삭제된 링크 포함 (`not_found`) */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "not_found",
                 *         "message": "link not found"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description 링크 id */
        LinkId: number;
        /** @description 태그 id */
        TagId: number;
        /** @description 이전 응답의 `next_cursor` 값. 첫 페이지는 생략. 불투명(opaque) 토큰. */
        Cursor: string;
        /** @description 페이지 크기 */
        Limit: number;
        /** @description 태그 이름 필터 */
        TagFilter: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 프로세스 정상 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok"
                     *     }
                     */
                    "application/json": {
                        /** @constant */
                        status: "ok";
                    };
                };
            };
        };
    };
    listLinks: {
        parameters: {
            query?: {
                /** @description 이전 응답의 `next_cursor` 값. 첫 페이지는 생략. 불투명(opaque) 토큰. */
                cursor?: components["parameters"]["Cursor"];
                /** @description 페이지 크기 */
                limit?: components["parameters"]["Limit"];
                /** @description 태그 이름 필터 */
                tag?: components["parameters"]["TagFilter"];
                /** @description 링크 상태 필터 */
                status?: components["schemas"]["LinkStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 링크 목록 페이지 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    createLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkInput"];
            };
        };
        responses: {
            /** @description 동일 `url_hash`가 이미 존재 — 새로 만들지 않고 기존 id 반환 (멱등) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": 987,
                     *       "duplicate": true
                     *     }
                     */
                    "application/json": {
                        id: number;
                        /** @constant */
                        duplicate: true;
                    };
                };
            };
            /** @description 신규 저장 완료 (scrape 잡 enqueue됨) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": 1234,
                     *       "status": "pending",
                     *       "created_at": 1752980000
                     *     }
                     */
                    "application/json": {
                        id: number;
                        status: components["schemas"]["LinkStatus"];
                        created_at: components["schemas"]["EpochSeconds"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 링크 id */
                id: components["parameters"]["LinkId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 링크 상세 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 링크 id */
                id: components["parameters"]["LinkId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 삭제 완료 (본문 없음) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 링크 id */
                id: components["parameters"]["LinkId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkUpdateInput"];
            };
        };
        responses: {
            /** @description 수정 반영된 링크 상세 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    retryLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 링크 id */
                id: components["parameters"]["LinkId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 재-enqueue 수락 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": 1234,
                     *       "status": "pending"
                     *     }
                     */
                    "application/json": {
                        id: number;
                        status: components["schemas"]["LinkStatus"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listTags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 태그 사전 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createTag: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagInput"] & unknown;
            };
        };
        responses: {
            /** @description 생성된 태그 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 태그 id */
                id: components["parameters"]["TagId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 삭제 완료 (본문 없음) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 태그 id */
                id: components["parameters"]["TagId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagInput"];
            };
        };
        responses: {
            /** @description 수정된 태그 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    search: {
        parameters: {
            query: {
                /** @description 검색어. 3자 이상 = FTS5, 3자 미만 = LIKE 폴백 (400 아님). */
                q: string;
                /** @description 태그 이름 필터 */
                tag?: components["parameters"]["TagFilter"];
                /** @description created_at 범위 시작 (unix epoch 초) */
                from?: number;
                /** @description created_at 범위 끝 (unix epoch 초) */
                to?: number;
                /** @description 이전 응답의 `next_cursor` 값. 첫 페이지는 생략. 불투명(opaque) 토큰 — 목록 커서와 검색 커서는 형식이 달라 서로 호환되지 않는다 (형식 불일치는 400). FTS 모드 커서는 bm25 rank 기반이라 페이지 사이에 쓰기가 발생하면 FTS 페이지 경계가 이동할 수 있다 (단일 사용자 규모에서 허용). */
                cursor?: string;
                /** @description 페이지 크기 */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 검색 결과 페이지 (`mode`로 검색 경로 표시) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 통계 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stats"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getThumb: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description url_hash 앞 2자리 (hex)
                 * @example a3
                 */
                dir: string;
                /**
                 * @description `{url_hash}.jpg` 파일명
                 * @example a3f1b2c4d5e6f7a8a3f1b2c4d5e6f7a8a3f1b2c4d5e6f7a8a3f1b2c4d5e6f7a8.jpg
                 */
                file: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 썸네일 이미지 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
}
