-- 태그 사전 시드 30개 (docs/v2/05-DATA-SCHEMA.md §7)
-- aliases는 Phase A 문자열·동의어 매칭의 재료 — 영문/한글 표기와 흔한 동의어 포함.
INSERT INTO tags (name, aliases) VALUES
  ('dev',          '["개발","programming","coding","코딩","개발자"]'),
  ('golang',       '["go","고랭","고언어"]'),
  ('kubernetes',   '["k8s","쿠버네티스","쿠버"]'),
  ('ios',          '["아이오에스","swiftui","애플","apple"]'),
  ('swift',        '["스위프트"]'),
  ('python',       '["파이썬"]'),
  ('rust',         '["러스트"]'),
  ('javascript',   '["js","자바스크립트","typescript","ts","타입스크립트"]'),
  ('frontend',     '["프론트엔드","프론트","react","리액트","css"]'),
  ('backend',      '["백엔드","서버","server","api"]'),
  ('database',     '["db","데이터베이스","sql","sqlite","postgres"]'),
  ('devops',       '["데브옵스","ci/cd","docker","도커","인프라","infra"]'),
  ('security',     '["보안","시큐리티","해킹","hacking"]'),
  ('opensource',   '["오픈소스","open source","github","깃허브"]'),
  ('ai',           '["인공지능","머신러닝","machine learning","ml","딥러닝","deep learning"]'),
  ('llm',          '["대규모 언어 모델","gpt","claude","챗지피티","chatgpt","프롬프트"]'),
  ('data',         '["데이터","데이터 분석","analytics","통계"]'),
  ('design',       '["디자인","ui","ux","피그마","figma"]'),
  ('article',      '["아티클","글","블로그","blog","포스트"]'),
  ('video',        '["영상","동영상","유튜브","youtube"]'),
  ('tutorial',     '["튜토리얼","강의","가이드","how-to","입문"]'),
  ('news',         '["뉴스","소식","속보"]'),
  ('science',      '["과학","연구","paper","논문"]'),
  ('finance',      '["금융","투자","경제","재테크","주식"]'),
  ('career',       '["커리어","이직","취업","면접","이력서"]'),
  ('productivity', '["생산성","워크플로우","workflow","도구","tools"]'),
  ('book',         '["책","독서","서평","reading"]'),
  ('podcast',      '["팟캐스트","오디오"]'),
  ('travel',       '["여행","여행지"]'),
  ('life',         '["라이프","일상","생활"]');
