import Foundation

/// 화면 문자열 사전. 키는 `화면.무엇` 꼴이고 `L.t()`가 읽는다.
///
/// **두 로케일의 키 집합은 같아야 한다.** `just ios-i18n-check`가 그것과, 소스가 쓰는데
/// 사전에 없는 키와, 사전에 있는데 아무도 안 쓰는 키를 막는다. 웹의
/// `frontend/src/lib/strings.ts`와 같은 규칙이고 같은 이유다.
///
/// **웹과 겹치는 키는 값도 같아야 한다.** `just i18n-cross-check`가 대조한다 — 같은 문장을
/// 두 클라이언트가 다르게 말하는 것이 이 저장소가 반복해서 당한 갈라짐이다. 플랫폼 때문에
/// 갈라져야 하는 것(마우스는 click, 손가락은 tap)만 그 검사기의 허용 목록에 있다.
enum Strings {
    static let table: [String: [String: String]] = [
        "ko": [
            "common.authFailed": "인증에 실패했습니다.",
            "common.cancel": "취소",
            "common.close": "닫기",
            "common.collectFailed": "수집하지 못했습니다.",
            "common.delete": "삭제",
            "common.deleted": "삭제했습니다.",
            "common.done": "확인",
            "common.error": "오류",
            "common.last30Days": "최근 30일",
            "common.linkNotFound": "링크를 찾을 수 없습니다.",
            "common.loadFailed": "불러오지 못했습니다",
            "common.note": "메모",
            "common.openOriginal": "원문 열기",
            "common.openSettings": "설정 열기",
            "common.retry": "재시도",
            "common.save": "저장",
            "common.share": "공유",
            "common.tags": "태그",
            "common.tryAgain": "다시 시도",
            "common.undo": "실행 취소",
            "detail.attachTags": "태그 붙이기",
            "detail.deleteTitle": "이 링크를 삭제할까요?",
            "detail.editTags": "고치기",
            "detail.loadFailed": "불러오지 못했습니다",
            "detail.metaAuthor": "작성",
            "detail.metaLength": "분량",
            "detail.metaOpened": "열람",
            "detail.notePlaceholder": "왜 담았는지 한 줄",
            "detail.saveFailed": "저장하지 못했습니다: {error}",
            "detail.saveNote": "메모 저장",
            "detail.wordCount": "{n}단어",
            "detail.wordCountOne": "{n}단어",
            "inspector.metaSaved": "저장",
            "list.density": "밀도",
            "list.densityCard": "카드",
            "list.densityCompact": "조밀",
            "list.densityToggle": "{mode}로 보기",
            "list.emptyDescShare": "다른 앱에서 공유 시트로 보내거나, 여기서 주소를 붙여넣어 저장하세요.",
            "list.emptyTitle": "아직 모아둔 것이 없습니다",
            "list.filterFailed": "수집 실패만",
            "list.filterTag": "태그: {name}",
            "list.loadFailed": "목록을 불러오지 못했습니다",
            "list.retryFailed": "다시 시도하지 못했습니다.",
            "list.retryFailedHttp": "다시 시도하지 못했습니다 (HTTP {status}).",
            "list.retryNotAllowed": "다시 시도할 수 없는 링크입니다.",
            "list.undoFailed": "되돌리지 못했습니다.",
            "list.undoFailedHttp": "되돌리지 못했습니다 (HTTP {status}).",
            "nav.list": "목록",
            "nav.saveLink": "링크 저장",
            "nav.stats": "통계",
            "notify.channelMissing": "공유 저장 결과를 알릴 통로가 없습니다 (App Group 미설정)",
            "notify.dropped": "알림이 꺼져 있어 공유 저장 결과를 알 수 없습니다 ({n}건)",
            "notify.firstSaved": "처음 저장",
            "notify.duplicate": "이미 저장된 링크",
            "notify.failed": "저장하지 못했습니다",
            "notify.saved": "저장했습니다",
            "notify.tagFailed": "태그 실패",
            "rhythm.axisStart": "30일 전",
            "rhythm.collected": "무엇을 모았나",
            "rhythm.collectedHint": "누르면 그 목록으로",
            "rhythm.daysSaved": "{count}일 저장",
            "rhythm.daysSavedOne": "{count}일 저장",
            "rhythm.emptyBody": "링크를 저장하면 여기에 리듬이 쌓입니다.",
            "rhythm.emptyTitle": "아직 볼 통계가 없습니다",
            "rhythm.goalMet": "{n}일 연속 — 4주 목표를 넘겼습니다",
            "rhythm.goalMetCapped": "{n}일 이상 연속 — 4주 목표를 넘겼습니다 (30일 창 상한)",
            "rhythm.goalProgress": "{n}일 연속 — 4주(28일)까지 {count}일 남았어요",
            "rhythm.goalProgressOne": "{n}일 연속 — 4주(28일)까지 {count}일 남았어요",
            "rhythm.goalStart": "오늘 하나 저장하면 연속이 시작돼요",
            "rhythm.narrativeActive": "최근 30일 가운데 {n}일 저장했어요.",
            "rhythm.narrativeLastDaysAgo": "마지막은 {n}일 전이에요.",
            "rhythm.narrativeLastYesterday": "마지막은 어제예요.",
            "rhythm.narrativeNoRecent": "최근 30일에는 저장한 게 없어요. 지금까지 {count}개를 모았어요.",
            "rhythm.narrativeNoRecentOne": "최근 30일에는 저장한 게 없어요. 지금까지 {count}개를 모았어요.",
            "rhythm.narrativeStreak": "지금 {n}일째 이어가고 있어요.",
            "rhythm.narrativeStreakCapped": "30일 이상 이어가고 있어요.",
            "resurface.spine": "잊고 있던 것",
            "save.autofillHint": "제목·설명·태그는 저장한 뒤 자동으로 채워집니다.",
            "save.checkUrl": "주소를 확인해 주세요.",
            "save.failedHttp": "저장하지 못했습니다 (HTTP {status}).",
            "save.notePlaceholder": "왜 저장했는지…",
            "save.pasteFromClipboard": "클립보드에서 붙여넣기",
            "save.serverFailed": "서버에서 저장하지 못했습니다.",
            "save.urlSection": "주소",
            "search.clear": "검색어 지우기",
            "search.failed": "검색하지 못했습니다",
            "search.likeNotice": "두 글자 이하는 제목·메모만 훑습니다. 세 글자부터 전문 검색으로 바뀝니다.",
            "search.moreFailed": "다음 결과를 불러오지 못했습니다",
            "search.noMatch": "“{q}”와 맞는 링크를 찾지 못했습니다.",
            "search.noResults": "결과가 없습니다",
            "search.placeholderFields": "제목 · 메모 · 태그",
            "settings.appearance": "모양",
            "settings.notifications": "저장 알림",
            "settings.notifyAllow": "알림 켜기",
            "settings.notifyFooter": "공유 시트로 저장하면 결과를 알림으로 알려줍니다.",
            "settings.notifyHeader": "알림",
            "settings.notifyNotAsked": "아직 묻지 않음",
            "settings.notifyOff": "꺼짐",
            "settings.notifyOn": "켜짐",
            "settings.notifyOpen": "iOS 설정에서 바꾸기",
            "settings.switchLanguage": "언어 바꾸기",
            "settings.theme": "테마",
            "settings.themeDark": "다크",
            "settings.themeFooter": "‘시스템’은 기기 설정을 그대로 따릅니다.",
            "settings.themeLight": "라이트",
            "settings.themeSystem": "시스템",
            "settings.title": "설정",
            "share.noAppGroup": "App Group 컨테이너를 열 수 없습니다",
            "share.noInput": "공유된 항목이 없습니다",
            "share.noURL": "URL을 찾을 수 없습니다",
            "stats.failedLinks": "수집에 실패한 링크 {count}개",
            "stats.failedLinksOne": "수집에 실패한 링크 {count}개",
            "status.appGroupUnavailable": "App Group 컨테이너를 열 수 없습니다 (entitlement 확인 필요)",
            "status.badServerAddress": "서버 주소를 해석할 수 없습니다: {addr}",
            "status.done": "완료",
            "status.failed": "실패",
            "status.pending": "대기",
            "status.retryWaiting": "재시도 대기 중",
            "status.scraping": "수집 중",
            "status.serverNotReady": "서버가 아직 준비되지 않았습니다.",
            "status.serverStartFailed": "서버를 시작하지 못했습니다",
            "status.serverStarting": "서버 시작 중…",
            "status.tagging": "태깅 중",
            "tags.facetCraft": "만드는 것",
            "tags.facetLife": "세상과 일상",
            "tags.facetMedia": "형식",
            "tags.facetNeutral": "분류 없음",
            "time.earlier": "이전",
            "time.hoursAgo": "{n}시간 전",
            "time.justNow": "방금",
            "time.minutesAgo": "{n}분 전",
            "time.month1": "1월",
            "time.month10": "10월",
            "time.month11": "11월",
            "time.month12": "12월",
            "time.month2": "2월",
            "time.month3": "3월",
            "time.month4": "4월",
            "time.month5": "5월",
            "time.month6": "6월",
            "time.month7": "7월",
            "time.month8": "8월",
            "time.month9": "9월",
            "time.monthDay": "{month} {d}일",
            "time.thisWeek": "이번 주",
            "time.timeOfDayAm": "오전 {h}:{mm}",
            "time.timeOfDayPm": "오후 {h}:{mm}",
            "time.today": "오늘",
            "time.yesterday": "어제",
            "widget.daysUnit": "일 연속",
            "widget.description": "연속 저장과 30일 리듬을 홈 화면에서 봅니다.",
            "widget.empty": "앱을 한 번 열면 여기에 연속이 나타나요",
            "widget.notYetToday": "오늘 아직",
            "widget.rhythm": "30일",
            "widget.savedToday": "오늘 저장함",
            "settings.backup": "백업",
            "settings.backupDone": "됐습니다",
            "settings.backupExport": "아카이브 내보내기",
            "settings.backupFailed": "안 됐습니다",
            "settings.backupFooter": "내보낸 파일 하나에 링크·태그·메모·검색 색인이 전부 들어갑니다. 폰을 잃으면 이 파일이 아카이브를 되살릴 유일한 방법입니다.",
            "settings.backupRestartNeeded": "앱을 완전히 닫았다 다시 열면 되돌려집니다.",
            "settings.backupRestore": "파일에서 되돌리기",
            "widget.resurface.desc": "잊고 있던 링크 하나를 홈 화면에서",
            "widget.resurface.empty": "저장한 지 일주일이 지나면 여기 나타나요",
            "widget.resurface.name": "다시 보기",
            "widget.resurface.title": "다시 볼까요",
            "widget.title": "연속 저장",
        ],
        "en": [
            "common.authFailed": "Authentication failed.",
            "common.cancel": "Cancel",
            "common.close": "Close",
            "common.collectFailed": "Could not collect this link.",
            "common.delete": "Delete",
            "common.deleted": "Deleted.",
            "common.done": "Done",
            "common.error": "Error",
            "common.last30Days": "Last 30 days",
            "common.linkNotFound": "Link not found.",
            "common.loadFailed": "Could not load",
            "common.note": "Note",
            "common.openOriginal": "Open original",
            "common.openSettings": "Open settings",
            "common.retry": "Retry",
            "common.save": "Save",
            "common.share": "Share",
            "common.tags": "Tags",
            "common.tryAgain": "Try again",
            "common.undo": "Undo",
            "detail.attachTags": "Add tags",
            "detail.deleteTitle": "Delete this link?",
            "detail.editTags": "Edit",
            "detail.loadFailed": "Could not load this link",
            "detail.metaAuthor": "Author",
            "detail.metaLength": "Length",
            "detail.metaOpened": "Opened",
            "detail.notePlaceholder": "One line on why you saved it",
            "detail.saveFailed": "Could not save: {error}",
            "detail.saveNote": "Save note",
            "detail.wordCount": "{n} words",
            "detail.wordCountOne": "1 word",
            "inspector.metaSaved": "Saved",
            "list.density": "Density",
            "list.densityCard": "Card",
            "list.densityCompact": "Compact",
            "list.densityToggle": "Switch to {mode}",
            "list.emptyDescShare": "Send one from another app's share sheet, or paste a URL here.",
            "list.emptyTitle": "Nothing saved yet",
            "list.filterFailed": "Failed only",
            "list.filterTag": "Tag: {name}",
            "list.loadFailed": "Could not load the list",
            "list.retryFailed": "Could not retry.",
            "list.retryFailedHttp": "Could not retry (HTTP {status}).",
            "list.retryNotAllowed": "This link cannot be retried.",
            "list.undoFailed": "Could not undo.",
            "list.undoFailedHttp": "Could not undo (HTTP {status}).",
            "nav.list": "List",
            "nav.saveLink": "Save a link",
            "nav.stats": "Stats",
            "notify.channelMissing": "No channel to report share saves (App Group not set up)",
            "notify.dropped": "Notifications are off, so share saves go unreported ({n})",
            "notify.firstSaved": "First saved",
            "notify.duplicate": "Already saved",
            "notify.failed": "Could not save",
            "notify.saved": "Saved",
            "notify.tagFailed": "Tagging failed",
            "rhythm.axisStart": "30 days ago",
            "rhythm.collected": "What you collect",
            "rhythm.collectedHint": "Tap to see the list",
            "rhythm.daysSaved": "1 day saved|{count} days saved",
            "rhythm.daysSavedOne": "1 day saved",
            "rhythm.emptyBody": "Save links and your rhythm builds up here.",
            "rhythm.emptyTitle": "No stats yet",
            "rhythm.goalMet": "{n}-day streak — past the 4-week goal",
            "rhythm.goalMetCapped": "{n}+ day streak — past the 4-week goal (30-day window cap)",
            "rhythm.goalProgress": "{n}-day streak — 1 day to 4 weeks (28 days)|{n}-day streak — {count} days to 4 weeks (28 days)",
            "rhythm.goalProgressOne": "{n}-day streak — 1 day to 4 weeks (28 days)",
            "rhythm.goalStart": "Save one today and the streak starts",
            "rhythm.narrativeActive": "Saved on {n} of the last 30 days.",
            "rhythm.narrativeLastDaysAgo": "The last one was {n} days ago.",
            "rhythm.narrativeLastYesterday": "The last one was yesterday.",
            "rhythm.narrativeNoRecent": "Nothing saved in the last 30 days. 1 link saved so far.|Nothing saved in the last 30 days. {count} links saved so far.",
            "rhythm.narrativeNoRecentOne": "Nothing saved in the last 30 days. 1 link saved so far.",
            "rhythm.narrativeStreak": "Day {n} of the current streak.",
            "rhythm.narrativeStreakCapped": "A streak of 30 days or more.",
            "resurface.spine": "You forgot about this",
            "save.autofillHint": "Title, description and tags fill themselves in after you save.",
            "save.checkUrl": "Check the URL.",
            "save.failedHttp": "Could not save (HTTP {status}).",
            "save.notePlaceholder": "Why you saved it…",
            "save.pasteFromClipboard": "Paste from clipboard",
            "save.serverFailed": "The server could not save it.",
            "save.urlSection": "URL",
            "search.clear": "Clear search",
            "search.failed": "Search failed",
            "search.likeNotice": "Two characters or fewer search titles and notes only. Full-text search starts at three.",
            "search.moreFailed": "Could not load more results",
            "search.noMatch": "Nothing matches “{q}”.",
            "search.noResults": "No results",
            "search.placeholderFields": "Title · note · tags",
            "settings.appearance": "Appearance",
            "settings.notifications": "Save notifications",
            "settings.notifyAllow": "Turn on notifications",
            "settings.notifyFooter": "When you save from the share sheet, the result arrives as a notification.",
            "settings.notifyHeader": "Notifications",
            "settings.notifyNotAsked": "Not asked yet",
            "settings.notifyOff": "Off",
            "settings.notifyOn": "On",
            "settings.notifyOpen": "Change in iOS Settings",
            "settings.switchLanguage": "Switch language",
            "settings.theme": "Theme",
            "settings.themeDark": "Dark",
            "settings.themeFooter": "“System” follows your device setting.",
            "settings.themeLight": "Light",
            "settings.themeSystem": "System",
            "settings.title": "Settings",
            "share.noAppGroup": "Cannot open the App Group container",
            "share.noInput": "Nothing was shared",
            "share.noURL": "No URL found",
            "stats.failedLinks": "{count} links failed to collect",
            "stats.failedLinksOne": "1 link failed to collect",
            "status.appGroupUnavailable": "Cannot open the App Group container (check the entitlement)",
            "status.badServerAddress": "Could not parse the server address: {addr}",
            "status.done": "Done",
            "status.failed": "Failed",
            "status.pending": "Pending",
            "status.retryWaiting": "Waiting to retry",
            "status.scraping": "Fetching",
            "status.serverNotReady": "The server is not ready yet.",
            "status.serverStartFailed": "Could not start the server",
            "status.serverStarting": "Starting the server…",
            "status.tagging": "Tagging",
            "tags.facetCraft": "Making",
            "tags.facetLife": "World & life",
            "tags.facetMedia": "Format",
            "tags.facetNeutral": "Uncategorized",
            "time.earlier": "Earlier",
            "time.hoursAgo": "{n}h ago",
            "time.justNow": "Just now",
            "time.minutesAgo": "{n}m ago",
            "time.month1": "Jan",
            "time.month10": "Oct",
            "time.month11": "Nov",
            "time.month12": "Dec",
            "time.month2": "Feb",
            "time.month3": "Mar",
            "time.month4": "Apr",
            "time.month5": "May",
            "time.month6": "Jun",
            "time.month7": "Jul",
            "time.month8": "Aug",
            "time.month9": "Sep",
            "time.monthDay": "{month} {d}",
            "time.thisWeek": "This week",
            "time.timeOfDayAm": "{h}:{mm} AM",
            "time.timeOfDayPm": "{h}:{mm} PM",
            "time.today": "Today",
            "time.yesterday": "Yesterday",
            "widget.daysUnit": "day streak",
            "widget.description": "Your streak and 30-day rhythm on the home screen.",
            "widget.empty": "Open the app once and your streak appears here",
            "settings.backup": "Backup",
            "settings.backupDone": "Done",
            "settings.backupExport": "Export archive",
            "settings.backupFailed": "That did not work",
            "settings.backupFooter": "One file holds every link, tag, note and the search index. If you lose your phone, this file is the only way back.",
            "settings.backupRestartNeeded": "Close the app completely and open it again to finish restoring.",
            "settings.backupRestore": "Restore from a file",
            "widget.resurface.desc": "One forgotten link, on your home screen",
            "widget.resurface.empty": "Links show up here a week after you save them",
            "widget.resurface.name": "Another look",
            "widget.resurface.title": "Worth another look",
            "widget.notYetToday": "Nothing today yet",
            "widget.rhythm": "30 days",
            "widget.savedToday": "Saved today",
            "widget.title": "Streak",
        ],
    ]
}
