// testdata/cover-ops.json 생성기 — 웹 구현이 **원본**이고 이 파일이 그것을 굳힌다.
//
//   cd frontend && node_modules/.bin/vite-node ../scripts/gen_cover_ops.ts > ../testdata/cover-ops.json
//
// 손으로 고치지 말 것. 무늬를 바꿨으면 이걸 다시 돌리고, 그러면 iOS 테스트가 빨개져서
// 양쪽을 같이 고치게 된다 — 그 강제가 이 파일의 존재 이유다.
import { coverGeometry, coverPattern } from '../frontend/src/lib/covers'

const CASES: [string, number, number][] = [
  ['supabase.com', 320, 200],   // hatch — 대각선
  ['go.dev', 320, 200],
  ['github.com', 320, 200],
  ['news.ycombinator.com', 320, 200],
  ['react.dev', 260, 160],
  ['tailwindcss.com', 180, 120],
  ['stripe.com', 240, 150],
  ['', 320, 200],
]

const r3 = (n: number) => Math.round(n * 1000) / 1000
const cases = CASES.map(([domain, w, h]) => {
  const p = coverPattern(domain)
  const g = coverGeometry(p, w, h)
  return {
    domain, w, h,
    kind: p.kind, step: p.step, variant: p.variant,
    alpha: g.alpha, lineWidth: g.lineWidth, rotate: g.rotate, mode: g.mode,
    ops: g.ops.map((o) =>
      Object.fromEntries(Object.entries(o).map(([k, v]) => [k, typeof v === 'number' ? r3(v) : v])),
    ),
  }
})

console.log(
  JSON.stringify(
    {
      note: 'Cover drawing as primitives. Generated by scripts/gen_cover_ops.ts from frontend/src/lib/covers.ts; read by frontend/src/lib/covers.test.ts and ios/PushPointTests/CoverGeometryTests.swift. The two clients agreed on pattern parameters while drawing four different pictures from them — this is what makes the marks themselves comparable.',
      cases,
    },
    null,
    1,
  ),
)
