// UI 문자열 사전. 키는 `화면.무엇` 꼴이고, `i18n.ts`의 `t()`가 읽는다.
//
// **두 로케일의 키 집합은 같아야 한다.** `just web-i18n-check`가 그것과, 소스가 쓰는데
// 사전에 없는 키와, 사전에 있는데 아무도 안 쓰는 키를 막는다. site/copy.js와 같은 규칙이고
// 같은 이유다 — 손으로 관리하는 두 벌은 갈라지고, 갈라져도 양쪽 다 정상으로 보인다.
//
// 영어에 `|`가 있는 값은 단수|복수다. `t(key, { count })`가 갈라 쓴다. 한국어는 복수
// 일치가 없어 대개 `|`가 없고, 그래서 복수는 **키가 아니라 값의 성질**로 두었다.

export const STRINGS: Record<string, Record<string, string>> = {
  ko: {
    'common.add': '추가',
    'common.all': '전체',
    'common.cancel': '취소',
    'common.clearFilters': '필터 해제',
    'common.close': '닫기',
    'common.collectFailed': '수집하지 못했습니다.',
    'common.delete': '삭제',
    'common.deleted': '삭제했습니다.',
    'common.edit': '편집',
    'common.emptyResponse': '서버 응답이 비어 있습니다.',
    'common.error': '오류',
    'common.hasNote': '메모 있음',
    'common.invalidInput': '입력이 올바르지 않습니다.',
    'common.last30Days': '최근 30일',
    'common.loadMore': '더 보기',
    'common.loading': '불러오는 중…',
    'common.note': '메모',
    'common.open': '열기',
    'common.openDetail': '{title} 상세 열기',
    'common.openOriginal': '원문 열기',
    'common.openSettings': '설정 열기',
    'common.optional': '(선택)',
    'common.requestFailed': '요청에 실패했습니다.',
    'common.retry': '재시도',
    'common.save': '저장',
    'common.saved': '저장됨',
    'common.sort': '정렬',
    'common.tags': '태그',
    'common.tryAgain': '다시 시도',
    'common.undoRecollect': '되돌리기 — 다시 수집됩니다',
    'common.video': '동영상',
    'inspector.description': '설명',
    'inspector.goneDesc': '이 링크는 더 이상 존재하지 않습니다.',
    'inspector.goneTitle': '삭제되었거나 없는 링크입니다',
    'inspector.jobs': '잡',
    'inspector.meta': '메타',
    'inspector.metaAuthor': '작성자',
    'inspector.metaKind': '종류',
    'inspector.metaLang': '언어',
    'inspector.metaLength': '길이',
    'inspector.metaOpened': '마지막 열람',
    'inspector.metaPublished': '발행',
    'inspector.metaSaved': '저장',
    'inspector.notePlaceholder': '나중에 왜 저장했는지 적어 두세요',
    'inspector.summary': '요약',
    'inspector.tagCandidates': '태그 후보',
    'inspector.tagNotInDictionary': '은 사전에 없습니다 · 추가하고 붙이기',
    'inspector.tagSearch': '태그 검색',
    'inspector.tagSearchHint': '이름을 입력해 태그를 찾으세요',
    'inspector.wordCount': '{n} 단어',
    'list.emptyDesc': 'URL을 붙여넣으면 제목과 태그가 자동으로 채워집니다.',
    'list.emptyFailedDesc': '모든 링크가 정상 처리되었습니다.',
    'list.emptyFailedTitle': '실패한 링크가 없습니다',
    'list.emptyFilterDesc': '선택한 태그·상태 조합에 해당하는 항목이 없습니다.',
    'list.emptyFilterTitle': '조건에 맞는 링크가 없습니다',
    'list.emptyTitle': '아직 모아둔 것이 없습니다',
    'list.groupCount': '{count}건',
    'list.saveCta': '링크 저장하기',
    'list.unopened': '안 연 것',
    'nav.list': '목록',
    'nav.saveLink': '링크 저장',
    'nav.search': '검색',
    'nav.settings': '설정',
    'nav.skipToContent': '본문으로 건너뛰기',
    'nav.tags': '태그',
    'rhythm.axisStart': '30일 전',
    'rhythm.collected': '무엇을 모았나',
    'rhythm.collectedHint': '누르면 그 목록으로',
    'rhythm.daysSaved': '{count}일 저장',
    'rhythm.emptyBody': '링크를 저장하면 여기에 리듬이 쌓입니다.',
    'rhythm.emptyTitle': '아직 볼 통계가 없습니다',
    'rhythm.failedLinks': '수집에 실패한 링크 {count}개 — 다시 시도하기',
    'rhythm.goalMet': '{n}일 연속 — 4주 목표를 넘겼습니다',
    'rhythm.goalMetCapped': '{n}일 이상 연속 — 4주 목표를 넘겼습니다 (30일 창 상한)',
    'rhythm.goalProgress': '{n}일 연속 — 4주(28일)까지 {count}일 남았어요',
    'rhythm.goalStart': '오늘 하나 저장하면 연속이 시작돼요',
    'rhythm.loadFailed': '통계를 불러오지 못했습니다.',
    'rhythm.narrativeActive': '최근 30일 가운데 {n}일 저장했어요.',
    'rhythm.narrativeLastDaysAgo': '마지막은 {n}일 전이에요.',
    'rhythm.narrativeLastYesterday': '마지막은 어제예요.',
    'rhythm.narrativeNoRecent': '최근 30일에는 저장한 게 없어요. 지금까지 {count}개를 모았어요.',
    'rhythm.narrativeStreak': '지금 {n}일째 이어가고 있어요.',
    'rhythm.narrativeStreakCapped': '30일 이상 이어가고 있어요.',
    'rhythm.title': '리듬',
    'rhythm.total': '전체',
    'save.duplicate': '이미 저장한 링크입니다.',
    'save.enterKeyInSettings': '설정에서 API 키를 입력하세요.',
    'save.keyRequired': 'API 키가 필요합니다. 설정에서 입력하세요.',
    'save.noteAria': '메모 (선택)',
    'save.notePlaceholder': '왜 저장했는지…',
    'save.offline': '서버에 연결할 수 없습니다. 저장이 비활성화됩니다.',
    'save.urlAria': '저장할 URL',
    'save.urlRequired': 'URL을 입력하세요.',
    'save.urlScheme': 'http:// 또는 https:// 로 시작하는 URL이어야 합니다.',
    'search.clear': '검색어 지우기',
    'search.metaFts': 'FTS5 · bm25 정렬 · 불러온 {count}건',
    'search.metaLike': 'LIKE 폴백 · 최신순 · 불러온 {count}건',
    'search.noResultsDesc': '검색어나 필터를 바꿔 보세요.',
    'search.noResultsTitle': '"{q}"에 해당하는 링크가 없습니다',
    'search.period': '기간',
    'search.period7d': '최근 7일',
    'search.periodFilter': '기간 필터',
    'search.periodYear': '올해',
    'search.placeholder': '검색하거나 이동합니다',
    'search.promptDesc': '제목·메모·본문에서 찾습니다.',
    'search.promptTitle': '검색어를 입력하세요',
    'search.queryLabel': '검색어',
    'search.searching': '검색 중…',
    'search.tag': '태그',
    'search.tagFilter': '태그 필터',
    'settings.apiKey': 'API 키',
    'settings.appearance': '모양',
    'settings.checkConnection': '연결 확인',
    'settings.checkUnauthorized': '서버 정상 · 키 불일치 (401)',
    'settings.checkValid': '서버 정상 · 키 유효',
    'settings.checking': '확인 중…',
    'settings.connection': '연결',
    'settings.copied': '{label}를 복사했습니다',
    'settings.copyApiKey': 'API 키 복사',
    'settings.copyEmpty': '{label}가 비어 있습니다 — 먼저 위에서 API 키를 저장하세요',
    'settings.copyFailed': '복사에 실패했습니다. 직접 입력하세요: {value}',
    'settings.copyServerAddress': '서버 주소 복사',
    'settings.extensionIntro': '브라우저 확장을 설치하면 보고 있는 페이지를 {body} 저장합니다. 서버가 직접 가져올 수 없는 페이지(자바스크립트로 그리는 사이트, 봇 차단, 로그인이 필요한 글)도 그대로 담깁니다.',
    'settings.extensionIntroBody': '본문까지',
    'settings.extensionStep1': 'Chrome 주소창에 {url} 입력 → 우측 상단 개발자 모드 켜기',
    'settings.extensionStep2': '“압축해제된 확장 프로그램을 로드” → 저장소의 {dir} 폴더 선택',
    'settings.extensionStep3': '확장 옵션에서 아래 두 값을 붙여넣기',
    'settings.hideKey': 'API 키 숨기기',
    'settings.keyHint': '서버의 {env} 값입니다. 이 브라우저의 localStorage에 저장되어 모든 요청에 {header}로 붙습니다.',
    'settings.reenterKey': '키 다시 입력',
    'settings.saveKeyFirst': '변경한 키를 먼저 저장하세요',
    'settings.saveTools': '저장 도구',
    'settings.serverAddress': '서버 주소',
    'settings.showKey': 'API 키 표시',
    'settings.switchLanguage': '언어 바꾸기',
    'settings.switchToDark': '다크 모드로 전환',
    'settings.switchToLight': '라이트 모드로 전환',
    'settings.theme': '테마',
    'settings.themeDark': '다크',
    'settings.themeLight': '라이트',
    'settings.themeSystem': '시스템',
    'settings.title': '설정',
    'sheets.backupAdvice': '데이터는 SQLite 파일 하나라 그 파일을 복사하는 편이 더 완전합니다.',
    'sheets.checking': '확인 중…',
    'sheets.connectOnce': '연결은 터미널에서 한 번만 하면 됩니다. 구글 승인을 브라우저에서 직접 밟아야 해서 이 화면이 대신할 수 없습니다.',
    'sheets.connected': '연결됨',
    'sheets.exportIntro': '저장한 링크를 Google 스프레드시트로 내보낼 수 있습니다. 시트에서 걸러 보거나 남에게 보여줄 때 쓰는 자리입니다.',
    'sheets.lastRunFailed': '{when}에 시도했다가 실패',
    'sheets.lastRunOk': '{when} · {count}건',
    'sheets.lastSyncFailed': '마지막 동기화 실패: {error}',
    'sheets.neverSynced': '아직 한 번도 보내지 않았습니다',
    'sheets.notBackup': '백업은 아닙니다.',
    'sheets.openSheet': '시트 열기',
    'sheets.rewriteWhole': '매번 시트를 통째로 다시 씁니다.',
    'sheets.rewriteWhy': '태그를 고치거나 링크를 지운 것이 반영돼야 하기 때문입니다. 그래서 시트에 손으로 적은 것은 지워집니다. 메모를 남기려면 다른 탭에 하세요.',
    'sheets.setupHint': '스크립트를 클립보드에 넣고 브라우저를 열어 줍니다. 붙여넣고 배포한 뒤 URL만 되돌려 주면 끝입니다.',
    'sheets.syncNow': '지금 동기화',
    'sheets.syncRequestFailed': '동기화 요청이 실패했습니다.',
    'sheets.syncing': '보내는 중…',
    'sheets.title': '스프레드시트',
    'shortcuts.actionDelete': '링크 소프트 삭제 + 실행취소 토스트',
    'shortcuts.actionEditNote': '인스펙터를 열고 메모 입력에 포커스',
    'shortcuts.actionEditTags': '인스펙터를 열고 태그 입력에 포커스',
    'shortcuts.actionEscape': '팔레트 → 컴포저 → 인스펙터 → 검색어 순으로 하나씩 닫기/비우기',
    'shortcuts.actionFocusSearch': '검색 입력 포커스(목록에서는 검색으로 이동하며 포커스)',
    'shortcuts.actionNextRow': '다음 행으로 커서 이동',
    'shortcuts.actionOpenComposer': '저장 컴포저 열고 URL 필드 포커스',
    'shortcuts.actionOpenInspector': '커서 행의 인스펙터 열기',
    'shortcuts.actionOpenOriginal': '원문(url)을 새 탭으로 열기 — 원문 열기는 이 키 하나뿐이다',
    'shortcuts.actionPalette': '커맨드 팔레트 열기(이동 + 검색 + 태그 점프)',
    'shortcuts.actionPasteSave': '클립보드가 http(s)://로 시작하면 즉시 저장(실행취소 토스트)',
    'shortcuts.actionPrevRow': '이전 행으로 커서 이동',
    'shortcuts.actionRetry': 'status가 \'failed\'일 때만 재시도',
    'shortcuts.actionSubmitForm': '그 폼을 즉시 제출/저장(blur·버튼 클릭 대기 없이)',
    'shortcuts.actionToggleOverlay': '이 단축키 오버레이 열기/닫기',
    'shortcuts.scopeGlobal': '전역',
    'shortcuts.scopeListSearch': '목록·검색',
    'shortcuts.scopeOutsideInput': '입력 밖',
    'shortcuts.scopeRowInspector': '행 커서·인스펙터',
    'shortcuts.scopeSaveForm': '저장 폼 안',
    'shortcuts.title': '키보드 단축키',
    'status.apiKeyRequired': 'API 키가 필요합니다',
    'status.apiKeyState': 'API 키 상태',
    'status.connectionState': '연결 상태',
    'status.done': '완료',
    'status.failed': '실패',
    'status.filter': '상태 필터',
    'status.label': '상태',
    'status.offline': '서버에 연결할 수 없습니다. 저장·수정이 비활성화됩니다.',
    'status.pending': '대기',
    'status.retryWaiting': '재시도 대기 중',
    'status.scraping': '수집 중',
    'status.serverUnreachable': '서버에 연결할 수 없습니다',
    'status.tagging': '태깅 중',
    'tags.add': '태그 추가',
    'tags.addAlias': '별칭 추가',
    'tags.aliasHint': '별칭은 규칙 태거가 문자열로 매칭하는 대상입니다.',
    'tags.aliasPlaceholder': '별칭 입력 후 Enter',
    'tags.aliasesLabel': '별칭',
    'tags.count': '{count}개',
    'tags.deleteBody': '을(를) 삭제하면 링크 {n}건에서 이 태그가 함께 제거됩니다. 되돌릴 수 없습니다.',
    'tags.deleteTitle': '태그를 삭제할까요?',
    'tags.deleted': '"{name}"을(를) 삭제했습니다.',
    'tags.emptyDescription': '자동 태깅은 사전에 있는 태그만 붙입니다.',
    'tags.emptyTitle': '태그 사전이 비어 있습니다',
    'tags.facetCraft': '만드는 것',
    'tags.facetField': '분류',
    'tags.facetLife': '세상과 일상',
    'tags.facetMedia': '형식',
    'tags.facetNeutral': '분류 없음',
    'tags.facetSelectLabel': '분류(facet)',
    'tags.linkTotal': '링크 {n}건',
    'tags.nameLabel': '이름',
    'tags.nameRequired': '이름을 입력하세요.',
    'tags.nameTaken': '이미 있는 이름입니다.',
    'tags.newTagName': '새 태그 이름',
    'tags.removeAlias': '별칭 {alias} 제거',
    'tags.removeChip': '태그 제거',
    'tags.removeTag': '{name} 제거',
    'tags.sortByCount': '링크 수',
    'tags.sortByName': '이름',
    'tags.sortByRecent': '최근 저장순',
    'tags.tagName': '태그 이름',
    'tags.title': '태그 사전',
    'time.absolute': '{y}년 {month} {d}일 {hh}:{mi}',
    'time.durationHm': '{h}시간 {m}분',
    'time.durationMs': '{m}분 {s}초',
    'time.hoursAgo': '{n}시간 전',
    'time.justNow': '방금',
    'time.minutesAgo': '{n}분 전',
    'time.month1': '1월',
    'time.month10': '10월',
    'time.month11': '11월',
    'time.month12': '12월',
    'time.month2': '2월',
    'time.month3': '3월',
    'time.month4': '4월',
    'time.month5': '5월',
    'time.month6': '6월',
    'time.month7': '7월',
    'time.month8': '8월',
    'time.month9': '9월',
    'time.monthDay': '{month} {d}일',
    'time.monthYear': '{y}년 {month}',
    'time.thisWeek': '이번 주',
    'time.timeOfDayAm': '오전 {h}:{mm}',
    'time.timeOfDayPm': '오후 {h}:{mm}',
    'time.today': '오늘',
    'time.yesterday': '어제',
  },
  en: {
    'common.add': 'Add',
    'common.all': 'All',
    'common.cancel': 'Cancel',
    'common.clearFilters': 'Clear filters',
    'common.close': 'Close',
    'common.collectFailed': 'Could not collect this link.',
    'common.delete': 'Delete',
    'common.deleted': 'Deleted.',
    'common.edit': 'Edit',
    'common.emptyResponse': 'The server returned an empty response.',
    'common.error': 'Error',
    'common.hasNote': 'Has a note',
    'common.invalidInput': 'Invalid input.',
    'common.last30Days': 'Last 30 days',
    'common.loadMore': 'Load more',
    'common.loading': 'Loading…',
    'common.note': 'Note',
    'common.open': 'Open',
    'common.openDetail': 'Open details for {title}',
    'common.openOriginal': 'Open original',
    'common.openSettings': 'Open settings',
    'common.optional': '(optional)',
    'common.requestFailed': 'Request failed.',
    'common.retry': 'Retry',
    'common.save': 'Save',
    'common.saved': 'Saved',
    'common.sort': 'Sort',
    'common.tags': 'Tags',
    'common.tryAgain': 'Try again',
    'common.undoRecollect': 'Undo — it will be fetched again',
    'common.video': 'Video',
    'inspector.description': 'Description',
    'inspector.goneDesc': 'This link no longer exists.',
    'inspector.goneTitle': 'Link deleted or not found',
    'inspector.jobs': 'Jobs',
    'inspector.meta': 'Meta',
    'inspector.metaAuthor': 'Author',
    'inspector.metaKind': 'Type',
    'inspector.metaLang': 'Language',
    'inspector.metaLength': 'Length',
    'inspector.metaOpened': 'Last opened',
    'inspector.metaPublished': 'Published',
    'inspector.metaSaved': 'Saved',
    'inspector.notePlaceholder': 'Note why you saved this, for later',
    'inspector.summary': 'Summary',
    'inspector.tagCandidates': 'Tag suggestions',
    'inspector.tagNotInDictionary': 'not in dictionary · create and attach',
    'inspector.tagSearch': 'Search tags',
    'inspector.tagSearchHint': 'Type a name to find a tag',
    'inspector.wordCount': '1 word|{n} words',
    'list.emptyDesc': 'Paste a URL and the title and tags fill themselves in.',
    'list.emptyFailedDesc': 'Every link was processed.',
    'list.emptyFailedTitle': 'No failed links',
    'list.emptyFilterDesc': 'Nothing matches the selected tag and status.',
    'list.emptyFilterTitle': 'No links match',
    'list.emptyTitle': 'Nothing saved yet',
    'list.groupCount': '{count} link|{count} links',
    'list.saveCta': 'Save a link',
    'list.unopened': 'Unopened',
    'nav.list': 'List',
    'nav.saveLink': 'Save a link',
    'nav.search': 'Search',
    'nav.settings': 'Settings',
    'nav.skipToContent': 'Skip to content',
    'nav.tags': 'Tags',
    'rhythm.axisStart': '30 days ago',
    'rhythm.collected': 'What you collect',
    'rhythm.collectedHint': 'Click to see the list',
    'rhythm.daysSaved': '1 day saved|{count} days saved',
    'rhythm.emptyBody': 'Save links and your rhythm builds up here.',
    'rhythm.emptyTitle': 'No stats yet',
    'rhythm.failedLinks': '1 link failed to collect — retry|{count} links failed to collect — retry',
    'rhythm.goalMet': '{n}-day streak — past the 4-week goal',
    'rhythm.goalMetCapped': '{n}+ day streak — past the 4-week goal (30-day window cap)',
    'rhythm.goalProgress': '{n}-day streak — 1 day to 4 weeks (28 days)|{n}-day streak — {count} days to 4 weeks (28 days)',
    'rhythm.goalStart': 'Save one today and the streak starts',
    'rhythm.loadFailed': 'Could not load stats.',
    'rhythm.narrativeActive': 'Saved on {n} of the last 30 days.',
    'rhythm.narrativeLastDaysAgo': 'The last one was {n} days ago.',
    'rhythm.narrativeLastYesterday': 'The last one was yesterday.',
    'rhythm.narrativeNoRecent': 'Nothing saved in the last 30 days. 1 link saved so far.|Nothing saved in the last 30 days. {count} links saved so far.',
    'rhythm.narrativeStreak': 'Day {n} of the current streak.',
    'rhythm.narrativeStreakCapped': 'A streak of 30 days or more.',
    'rhythm.title': 'Rhythm',
    'rhythm.total': 'Total',
    'save.duplicate': 'Already saved.',
    'save.enterKeyInSettings': 'Enter your API key in Settings.',
    'save.keyRequired': 'An API key is required. Enter it in Settings.',
    'save.noteAria': 'Note (optional)',
    'save.notePlaceholder': 'Why you saved it…',
    'save.offline': 'Cannot reach the server. Saving is disabled.',
    'save.urlAria': 'URL to save',
    'save.urlRequired': 'Enter a URL.',
    'save.urlScheme': 'The URL must start with http:// or https://.',
    'search.clear': 'Clear search',
    'search.metaFts': 'FTS5 · bm25 ranked · {count} loaded',
    'search.metaLike': 'LIKE fallback · newest first · {count} loaded',
    'search.noResultsDesc': 'Try a different term or filter.',
    'search.noResultsTitle': 'No links match "{q}"',
    'search.period': 'Period',
    'search.period7d': 'Last 7 days',
    'search.periodFilter': 'Period filter',
    'search.periodYear': 'This year',
    'search.placeholder': 'Search or jump to a link',
    'search.promptDesc': 'Searches titles, notes, and page text.',
    'search.promptTitle': 'Type to search',
    'search.queryLabel': 'Search query',
    'search.searching': 'Searching…',
    'search.tag': 'Tag',
    'search.tagFilter': 'Tag filter',
    'settings.apiKey': 'API key',
    'settings.appearance': 'Appearance',
    'settings.checkConnection': 'Check connection',
    'settings.checkUnauthorized': 'Server up · key rejected (401)',
    'settings.checkValid': 'Server up · key valid',
    'settings.checking': 'Checking…',
    'settings.connection': 'Connection',
    'settings.copied': 'Copied the {label}',
    'settings.copyApiKey': 'Copy API key',
    'settings.copyEmpty': 'The {label} is empty — save your API key above first',
    'settings.copyFailed': 'Copy failed. Enter it by hand: {value}',
    'settings.copyServerAddress': 'Copy server address',
    'settings.extensionIntro': 'Install the browser extension and the page you are looking at is saved {body}. Pages the server cannot fetch on its own — JavaScript-rendered sites, bot walls, posts behind a login — are captured as they are.',
    'settings.extensionIntroBody': 'with its full text',
    'settings.extensionStep1': 'Type {url} in Chrome\'s address bar → turn on Developer mode, top right',
    'settings.extensionStep2': '“Load unpacked” → pick the {dir} folder in this repository',
    'settings.extensionStep3': 'Paste the two values below into the extension options',
    'settings.hideKey': 'Hide API key',
    'settings.keyHint': 'The server\'s {env} value. It is kept in this browser\'s localStorage and attached to every request as {header}.',
    'settings.reenterKey': 'Re-enter key',
    'settings.saveKeyFirst': 'Save the changed key first',
    'settings.saveTools': 'Saving tools',
    'settings.serverAddress': 'server address',
    'settings.showKey': 'Show API key',
    'settings.switchLanguage': 'Switch language',
    'settings.switchToDark': 'Switch to dark mode',
    'settings.switchToLight': 'Switch to light mode',
    'settings.theme': 'Theme',
    'settings.themeDark': 'Dark',
    'settings.themeLight': 'Light',
    'settings.themeSystem': 'System',
    'settings.title': 'Settings',
    'sheets.backupAdvice': 'The data is a single SQLite file, and copying that file is more complete.',
    'sheets.checking': 'Checking…',
    'sheets.connectOnce': 'Connecting is a one-time step in the terminal. The Google approval has to happen in your browser, so this screen cannot do it for you.',
    'sheets.connected': 'Connected',
    'sheets.exportIntro': 'Export your saved links to a Google Spreadsheet. It is a place to filter them or show them to someone.',
    'sheets.lastRunFailed': 'Tried at {when}, failed',
    'sheets.lastRunOk': '{when} · 1 row|{when} · {count} rows',
    'sheets.lastSyncFailed': 'Last sync failed: {error}',
    'sheets.neverSynced': 'Not sent yet',
    'sheets.notBackup': 'It is not a backup.',
    'sheets.openSheet': 'Open sheet',
    'sheets.rewriteWhole': 'Every sync rewrites the whole sheet.',
    'sheets.rewriteWhy': 'That is how a tag edit or a deleted link shows up. Anything you typed into the sheet by hand is erased — keep your notes on another tab.',
    'sheets.setupHint': 'It copies the script to your clipboard and opens the browser. Paste it, deploy, and hand back the URL — that is all.',
    'sheets.syncNow': 'Sync now',
    'sheets.syncRequestFailed': 'The sync request failed.',
    'sheets.syncing': 'Sending…',
    'sheets.title': 'Spreadsheet',
    'shortcuts.actionDelete': 'Soft-delete the link + undo toast',
    'shortcuts.actionEditNote': 'Open the inspector and focus the note field',
    'shortcuts.actionEditTags': 'Open the inspector and focus the tag field',
    'shortcuts.actionEscape': 'Close or clear one at a time: palette → composer → inspector → search query',
    'shortcuts.actionFocusSearch': 'Focus the search field (from the list, go to search and focus it)',
    'shortcuts.actionNextRow': 'Move the cursor to the next row',
    'shortcuts.actionOpenComposer': 'Open the save composer and focus the URL field',
    'shortcuts.actionOpenInspector': 'Open the inspector for the row under the cursor',
    'shortcuts.actionOpenOriginal': 'Open the original (url) in a new tab — the only key that does',
    'shortcuts.actionPalette': 'Open the command palette (navigate + search + tag jump)',
    'shortcuts.actionPasteSave': 'Save immediately if the clipboard starts with http(s):// (undo toast)',
    'shortcuts.actionPrevRow': 'Move the cursor to the previous row',
    'shortcuts.actionRetry': 'Retry — only when status is \'failed\'',
    'shortcuts.actionSubmitForm': 'Submit that form right away (no blur, no button click)',
    'shortcuts.actionToggleOverlay': 'Open or close this shortcut overlay',
    'shortcuts.scopeGlobal': 'Global',
    'shortcuts.scopeListSearch': 'List and search',
    'shortcuts.scopeOutsideInput': 'Outside inputs',
    'shortcuts.scopeRowInspector': 'Row cursor and inspector',
    'shortcuts.scopeSaveForm': 'In a save form',
    'shortcuts.title': 'Keyboard shortcuts',
    'status.apiKeyRequired': 'API key required',
    'status.apiKeyState': 'API key status',
    'status.connectionState': 'Connection status',
    'status.done': 'Done',
    'status.failed': 'Failed',
    'status.filter': 'Status filter',
    'status.label': 'Status',
    'status.offline': 'Cannot reach the server. Saving and editing are disabled.',
    'status.pending': 'Pending',
    'status.retryWaiting': 'Waiting to retry',
    'status.scraping': 'Fetching',
    'status.serverUnreachable': 'Cannot reach the server',
    'status.tagging': 'Tagging',
    'tags.add': 'Add tag',
    'tags.addAlias': 'Add alias',
    'tags.aliasHint': 'Aliases are the strings the rule tagger matches on.',
    'tags.aliasPlaceholder': 'Type an alias, press Enter',
    'tags.aliasesLabel': 'Aliases',
    'tags.count': '1 tag|{count} tags',
    'tags.deleteBody': ' will be removed from 1 link. This cannot be undone.| will be removed from {n} links. This cannot be undone.',
    'tags.deleteTitle': 'Delete this tag?',
    'tags.deleted': 'Deleted "{name}".',
    'tags.emptyDescription': 'Auto-tagging only attaches tags that are in the dictionary.',
    'tags.emptyTitle': 'The tag dictionary is empty',
    'tags.facetCraft': 'Making',
    'tags.facetField': 'Category',
    'tags.facetLife': 'World & life',
    'tags.facetMedia': 'Format',
    'tags.facetNeutral': 'Uncategorized',
    'tags.facetSelectLabel': 'Category (facet)',
    'tags.linkTotal': '1 link|{n} links',
    'tags.nameLabel': 'Name',
    'tags.nameRequired': 'Enter a name.',
    'tags.nameTaken': 'That name is already taken.',
    'tags.newTagName': 'New tag name',
    'tags.removeAlias': 'Remove alias {alias}',
    'tags.removeChip': 'Remove tag',
    'tags.removeTag': 'Remove {name}',
    'tags.sortByCount': 'Links',
    'tags.sortByName': 'Name',
    'tags.sortByRecent': 'Recent',
    'tags.tagName': 'Tag name',
    'tags.title': 'Tag dictionary',
    'time.absolute': '{month} {d}, {y} {hh}:{mi}',
    'time.durationHm': '{h}h {m}m',
    'time.durationMs': '{m}m {s}s',
    'time.hoursAgo': '{n}h ago',
    'time.justNow': 'Just now',
    'time.minutesAgo': '{n}m ago',
    'time.month1': 'Jan',
    'time.month10': 'Oct',
    'time.month11': 'Nov',
    'time.month12': 'Dec',
    'time.month2': 'Feb',
    'time.month3': 'Mar',
    'time.month4': 'Apr',
    'time.month5': 'May',
    'time.month6': 'Jun',
    'time.month7': 'Jul',
    'time.month8': 'Aug',
    'time.month9': 'Sep',
    'time.monthDay': '{month} {d}',
    'time.monthYear': '{month} {y}',
    'time.thisWeek': 'This week',
    'time.timeOfDayAm': '{h}:{mm} AM',
    'time.timeOfDayPm': '{h}:{mm} PM',
    'time.today': 'Today',
    'time.yesterday': 'Yesterday',
  },
}
